// flow-typed signature: 8ad02f945a832c455240016b93364fde
// flow-typed version: <<STUB>>/tachyons_v^4.9.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons' {
  declare module.exports: any;
}
